title: Nat Baca
logo: /assets/img/headshot.png
author: Nat Baca
description: "Hi! I'm Nat Baca. I'm interested in everything."
show_downloads: false
google_analytics: UA-179825035-1
remote_theme: pages-themes/minimal@v0.2.0
github:
  is_user_page: true
  owner_name: Nat Baca
  owner_url: http://github.com/natbaca/
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-font-awesome-sass
font-awesome:
  assets: true
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
exclude:
  - external
  - vendor
sass:
    sass_dir: _sass
    style: compressed
